import ProjectDescription

let workspace = Workspace(
  name: "PyeonHaeng",
  projects: [
    "Projects/App",
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .enabled(
      codeCoverageMode: .relevant
    )
  )
)
