name: iOS CI

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Unit Test
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.2"
      - name: Simulator List check
        run: xcrun simctl list devices
      - name: Execute Unit tests
        run: xcodebuild test -project SwiftCITest.xcodeproj -scheme SwiftCITest -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2'
